# Site settings
title: "Foostats | Classements buteurs | Foot amateur Suisse"
description: "Classements buteurs et équipes pour les championnats amateurs de football des cantons de Vaud et Fribourg"

baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://www.footstats.ch" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
name: ""

exclude: ["node_modules"]
gems:
  - jekyll-paginate

future: true
paginate: 12
paginate_path: "/page:num/"